name: Deploy at Development Environment

on:
  push:
    - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: make ci-setup
        
      - name: Run Tests
        run: make ci-tests

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: make ci-setup

      - name: Deploy
        env: 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make ci-deploy stage=dev
